#!/usr/bin/env bash
# logs into server and puts file
if [ $# -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

PATH_TO_FILE="$1"
IP="$2"
USERNAME="$3"
PATH_TO_SSH_KEY="$4"

SSH_OPTIONS="-o StrictHostKeyChecking=no"


scp $SSH_OPTIONS -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$IP:~/"


if [ $? -eq 0 ]; then
    echo "File transferred successfully to $USERNAME@$IP:~/"
else
    echo "File transfer failed"
fi
