#!/usr/bin/env bash
# debugging nginx port 80

# remove the default Nginx Configuration 
rm /etc/nginx/sites-enabled/default
# Configure Nginx to listen on 80
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
