#!/usr/bin/env bash
# Fixes a web server to run Nginx as the nginx user listening on port 8080.
file='/etc/nginx/sites-available/default'

# kill apache2 server
pkill -f apache2
chmod 777 /etc/nginx/nginx.conf
# update  port
sed -i 's/80/8080/g' $file

# restart nginx as nginx
sudo -u nginx service nginx restart
